# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: thelook_ecommerce
    table_name: orders
  timestamp_columns:
    event_timestamp_column: shipped_at
    ingestion_timestamp_column: created_at
    partitioned_checks_timestamp_source: event_timestamp
  checks:
    timeliness:
      days_since_most_recent_event:
        error:
          max_count: 0
      data_ingestion_delay:
        error:
          max_count: 0
      days_since_last_data_ingestion:
        error:
          max_count: 0
  checkpoints:
    daily:
      timeliness:
        daily_checkpoint_days_since_most_recent_event:
          error:
            max_count: 0
        daily_checkpoint_data_ingestion_delay:
          error:
            max_count: 0
        daily_checkpoint_days_since_last_data_ingestion:
          error:
            max_count: 0
    monthly:
      timeliness:
        monthly_checkpoint_days_since_most_recent_event:
          error:
            max_count: 0
        monthly_checkpoint_data_ingestion_delay:
          error:
            max_count: 0
        monthly_checkpoint_days_since_last_data_ingestion:
          error:
            max_count: 0
  columns:
    order_id:
      type_snapshot:
        column_type: INT64
        nullable: true
    user_id:
      type_snapshot:
        column_type: INT64
        nullable: true
    status:
      type_snapshot:
        column_type: STRING
        nullable: true
    gender:
      type_snapshot:
        column_type: STRING
        nullable: true
    created_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
    returned_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
    shipped_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
    delivered_at:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: true
    num_of_item:
      type_snapshot:
        column_type: INT64
        nullable: true
