# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: crypto_litecoin
    table_name: blocks
  filter: '`timestamp`>="2022-11-29"'
  timestamp_columns:
    event_timestamp_column: timestamp
    partitioned_checks_timestamp_source: event_timestamp
  checkpoints:
    daily:
      standard:
        daily_checkpoint_min_row_count:
          error:
            min_count: 3
          fatal:
            min_count: 1
  columns:
    hash:
      type_snapshot:
        column_type: STRING
        nullable: false
    size:
      type_snapshot:
        column_type: INT64
        nullable: true
    stripped_size:
      type_snapshot:
        column_type: INT64
        nullable: true
    weight:
      type_snapshot:
        column_type: INT64
        nullable: true
    number:
      type_snapshot:
        column_type: INT64
        nullable: false
    version:
      type_snapshot:
        column_type: INT64
        nullable: true
      checks:
        numeric:
          min_numbers_in_set_percent:
            parameters:
              values:
              - 1
            error:
              min_percent: 25.0
            warning:
              min_percent: 23.0
            fatal:
              min_percent: 12.0
    merkle_root:
      type_snapshot:
        column_type: STRING
        nullable: true
    timestamp:
      type_snapshot:
        column_type: TIMESTAMP
        nullable: false
    timestamp_month:
      type_snapshot:
        column_type: DATE
        nullable: false
    nonce:
      type_snapshot:
        column_type: STRING
        nullable: true
    bits:
      type_snapshot:
        column_type: STRING
        nullable: true
    coinbase_param:
      type_snapshot:
        column_type: STRING
        nullable: true
    transaction_count:
      type_snapshot:
        column_type: INT64
        nullable: true
      checkpoints:
        daily:
          numeric:
            daily_checkpoint_min_numbers_in_set_count:
              parameters:
                values:
                - 255
              error:
                min_count: 6
              fatal:
                min_count: 9
          strings:
            daily_checkpoint_min_string_boolean_placeholder_percent:
              error:
                min_percent: 5.0
              fatal:
                min_percent: 10.0
