# yaml-language-server: $schema=https://cloud.dqo.ai/dqo-yaml-schema/TableYaml-schema.json
apiVersion: dqo/v1
kind: table
spec:
  target:
    schema_name: maven_restaurant_ratings
    table_name: consumers
  timestamp_columns:
    event_timestamp_column: Drink_Level
    partitioned_checks_timestamp_source: event_timestamp
  columns:
    Consumer_ID:
      type_snapshot:
        column_type: STRING
        nullable: true
    City:
      type_snapshot:
        column_type: STRING
        nullable: true
    State:
      type_snapshot:
        column_type: STRING
        nullable: true
    Country:
      type_snapshot:
        column_type: STRING
        nullable: true
    Latitude:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    Longitude:
      type_snapshot:
        column_type: FLOAT64
        nullable: true
    Smoker:
      type_snapshot:
        column_type: BOOL
        nullable: true
    Drink_Level:
      type_snapshot:
        column_type: STRING
        nullable: true
    Transportation_Method:
      type_snapshot:
        column_type: STRING
        nullable: true
    Marital_Status:
      type_snapshot:
        column_type: STRING
        nullable: true
    Children:
      type_snapshot:
        column_type: STRING
        nullable: true
    Age:
      type_snapshot:
        column_type: INT64
        nullable: true
    Occupation:
      type_snapshot:
        column_type: STRING
        nullable: true
    Budget:
      type_snapshot:
        column_type: STRING
        nullable: true
